title: Project
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type:  text
  year:
    label: Year
    type:  text
  text:
    label: Text
    type:  textarea
  tags:
    label: Tags
    type:  tags
	date:
		label: Date
		type: date
		format: MM/DD/YYYY
		default: today
		override: true
